"""allinea modelli

Revision ID: 0c5201d7e976
Revises: c730805a8fcc
Create Date: 2026-10-02 19:25:31.025618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5201d7e976'
down_revision = 'c730805a8fcc'
branch_labels = None
depends_on = None


def upgrade():
    # Il DB di produzione potrebbe averla già persa (rimossa a mano): drop solo se presente.
    existing = {u["name"] for u in sa.inspect(op.get_bind()).get_unique_constraints('employee_contracts')}
    if 'unique_employee_contract' in existing:
        with op.batch_alter_table('employee_contracts', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('unique_employee_contract'), type_='unique')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_contracts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_employee_contract'), ['employee_id', 'contract_id'])

    # ### end Alembic commands ###
