"""added libemax id to employees

Revision ID: c730805a8fcc
Revises: 7171c0042710
Create Date: 2026-05-20 00:36:26.200817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c730805a8fcc'
down_revision = '7171c0042710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('libemax_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_employees_libemax_id', ['libemax_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employees_libemax_id', type_='unique')
        batch_op.drop_column('libemax_id')

    # ### end Alembic commands ###
