"""aggiunto campo note a workschedule

Revision ID: fdceeeba7cf8
Revises: de8e5e2941f6
Create Date: 2026-04-03 11:09:53.867824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdceeeba7cf8'
down_revision = 'de8e5e2941f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
